### ISSUE TITLE
Status of the 'ravenscar_full_stm32f4' project

### ISSUE THREAD

**Issue by GLHowell** [Fabien-Chouteau/ravenscar_full_stm32f4#1]
I'm very interested in basing my project on the code here.  I 've been unable to  compile the project using the tools in Alire.  Has anyone an example of a runtime.gpr file that builds?  Is this still an active project? Thanks, Gary.

**Comment by Fabien-Chouteau** [comment]
Hi @GLHowell this was just an experiment and I am not surprised it doesn't work. Right now I don't not plan to continue this experiment.

**Comment by GLHowell** [comment]
OK, understood. Thanks for the prompt response. - Gary
